hour_1 = int(input())
minute_1 = int(input())
second_1 = int(input())
time_1 = (hour_1 * 3600) + (minute_1 * 60) + (second_1)
hour_2 = int(input())
minute_2 = int(input())
second_2 = int(input())
time_2 = (hour_2 * 3600) + (minute_2 * 60) + (second_2)
print(abs(time_1 - time_2))
